var nama = prompt('masukan nama')
alert('hai ' + nama + ' cantik 👋🏽')
alert('Selamat Ulang Tahun yaaa ' + nama)
alert('ciyee dah 18 tahun aja')
alert('semoga ' + nama + ' panjang umur')
alert('dan  sehat selalu yaaa') 
alert('ehmm masi suka dibuka nih kayanya')
alert('tapi gapapa sii hehe makasii dah mengapresiasi kadoku 🥰')
var mau = confirm('kamu mau kukasih hadiah nggaa?')
    if( mau === true ) {
        alert('okey sayang')
        var hehe = confirm('suka banget yaa sama kadonya sampe ga bosen"😚?')
            if(hehe === true){
                alert('hehe SAYANG BOLLY 9999999999999999999%💖')
                alert('Love u')
                alert('Update tanggal 19 maret, ciyee masi dibuka aja')
                alert('SEMANGAT YAA BELAJAR SIAPIN SNBT NYA BABY')
                alert('UNDIP psikologi menunggumu kak')
                alert('Goodjob dah bertahan sampe sejauh ini hehe')
                alert('Yg rajin belajarnya nanti kalo ketrima di undip kita meet up coyyy for the first time')
                alert('tapi kalo emng hasilnya berbeda its okey')
                alert('remember this,ill always support u')
                alert('my baby goodgirl bolly love u')
                alert('Haai sayang kita dah ketemu coyyyyy agustus keamren first seakrang dah sering ketemu hehe setiap minggu - 25-10-2023')
                alert('sayangku pasti bisa jadi orang yg berhasil')
                alert('berat pastinya yaa hehe')
                alert('apalagi akhirnya masuk di ums akuntansi')
                alert('jangan nyerah yaa cantik, sabar dan usaha rezeki gatau dimana')
                alert('dijalani dulu sebaik mungkin oteyy, love u, semngatttt uts nya mingdep!!!')
                alert('abis ni dipencet yaa itu')
            } else {
                alert('walaupun ku ga percaya benget kalo kamu milih cancel dengan jujur')
                alert('pokonya Rafly dah sayang banget sama Adinda Ari Salma')
                alert('jangan kemana-mana yaa sayang')
                alert('fuck with all the distance ')
                alert('beacuse i know')
                alert('in the end i have u, mwah')
                alert('abis ni dipencet yaa itu')}
    } else {
        alert('dih tai🖕')
        alert('tapi tetep kukasi')
        alert('karena gweh baik😌😒')
        alert('pencet tuh sana')
    }
